//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 07:04:24 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.provenance;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the de.muenchen.oss.oai.webservice.schema.response.provenance package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
     * package: de.muenchen.oss.oai.webservice.schema.response.provenance
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Provenance }
     */
    public Provenance createProvenance() {
        return new Provenance();
    }

    /**
     * Create an instance of {@link OriginDescriptionType }
     */
    public OriginDescriptionType createOriginDescriptionType() {
        return new OriginDescriptionType();
    }

}
