//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 07:04:24 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.provenance;

import jakarta.xml.bind.annotation.*;

/**
 * <p>
 * Java class for originDescriptionType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="originDescriptionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="baseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="datestamp" type="{http://www.openarchives.org/OAI/2.0/provenance}UTCdatetimeType"/&gt;
 *         &lt;element name="metadataNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="originDescription" type="{http://www.openarchives.org/OAI/2.0/provenance}originDescriptionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="harvestDate" use="required" type="{http://www.openarchives.org/OAI/2.0/provenance}UTCdatetimeType" /&gt;
 *       &lt;attribute name="altered" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "originDescriptionType", propOrder = {
                "baseURL",
                "identifier",
                "datestamp",
                "metadataNamespace",
                "originDescription"
        }
)
public class OriginDescriptionType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    public String baseURL;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    public String identifier;
    @XmlElement(required = true)
    public String datestamp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    public String metadataNamespace;
    public OriginDescriptionType originDescription;
    @XmlAttribute(name = "harvestDate", required = true)
    public String harvestDate;
    @XmlAttribute(name = "altered", required = true)
    public boolean altered;

    /**
     * Gets the value of the baseURL property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getBaseURL() {
        return baseURL;
    }

    /**
     * Sets the value of the baseURL property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setBaseURL(String value) {
        this.baseURL = value;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the datestamp property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the metadataNamespace property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMetadataNamespace() {
        return metadataNamespace;
    }

    /**
     * Sets the value of the metadataNamespace property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setMetadataNamespace(String value) {
        this.metadataNamespace = value;
    }

    /**
     * Gets the value of the originDescription property.
     *
     * @return possible object is
     *         {@link OriginDescriptionType }
     */
    public OriginDescriptionType getOriginDescription() {
        return originDescription;
    }

    /**
     * Sets the value of the originDescription property.
     *
     * @param value allowed object is
     *            {@link OriginDescriptionType }
     */
    public void setOriginDescription(OriginDescriptionType value) {
        this.originDescription = value;
    }

    /**
     * Gets the value of the harvestDate property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHarvestDate() {
        return harvestDate;
    }

    /**
     * Sets the value of the harvestDate property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setHarvestDate(String value) {
        this.harvestDate = value;
    }

    /**
     * Gets the value of the altered property.
     */
    public boolean isAltered() {
        return altered;
    }

    /**
     * Sets the value of the altered property.
     */
    public void setAltered(boolean value) {
        this.altered = value;
    }

}
