//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 07:04:24 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.provenance;

import jakarta.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="originDescription" type="{http://www.openarchives.org/OAI/2.0/provenance}originDescriptionType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "", propOrder = {
                "originDescription"
        }
)
@XmlRootElement(name = "provenance")
public class Provenance {

    @XmlElement(required = true)
    public OriginDescriptionType originDescription;

    /**
     * Gets the value of the originDescription property.
     *
     * @return possible object is
     *         {@link OriginDescriptionType }
     */
    public OriginDescriptionType getOriginDescription() {
        return originDescription;
    }

    /**
     * Sets the value of the originDescription property.
     *
     * @param value allowed object is
     *            {@link OriginDescriptionType }
     */
    public void setOriginDescription(OriginDescriptionType value) {
        this.originDescription = value;
    }

}
