//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.08.31 at 09:34:26 AM CEST
//

package de.muenchen.oss.oai.pmh.schema;

import de.muenchen.oss.oai.pmh.schema.rights.RightsManifestType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * The descriptionType is used for the description
 * element in Identify and for setDescription element in ListSets.
 * Content must be compliant with an XML Schema defined by a
 * community.
 *
 * <p>
 * Java class for descriptionType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="descriptionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;any namespace='##other'/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "descriptionType", propOrder = {
                "any"
        }
)
public class DescriptionType {

    @XmlElement
    public RightsManifestType rightsManifest;

    /**
     * Gets the value of the rightsManifest property.
     *
     * @return possible object is
     *         {@link RightsManifestType }
     */
    public Object getRightsManifest() {
        return rightsManifest;
    }

    /**
     * Sets the value of the rightsManifest property.
     *
     * @param rightsManifest allowed object is
     *            {@link RightsManifestType }
     */
    public void setRightsManifest(RightsManifestType rightsManifest) {
        this.rightsManifest = rightsManifest;
    }

}
