//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.08.31 at 09:34:26 AM CEST
//

package de.muenchen.oss.oai.pmh.schema;

import de.muenchen.oss.oai.pmh.schema.metadata.dublincore.OaiDcType;
import de.muenchen.oss.oai.pmh.schema.metadata.marc21.RecordType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Metadata must be expressed in XML that complies
 * with another XML Schema (namespace=#other). Metadata must be
 * explicitly qualified in the response.
 *
 * <p>
 * Java class for metadataType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="metadataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;any namespace='##other'/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "metadataType", propOrder = {
                "oaiDcType",
                "marc21Type"
        }
)
public class MetadataType {

    @XmlElement(name = "oai_dc:dc")
    public OaiDcType oaiDcType;

    @XmlElement(name = "record")
    public RecordType marc21Type;

    public OaiDcType getOaiDcType() {
        return oaiDcType;
    }

    public void setOaiDcType(OaiDcType oaiDcType) {
        this.oaiDcType = oaiDcType;
    }

    public RecordType getMarc21Type() {
        return marc21Type;
    }

    public void setMarc21Type(RecordType marc21Type) {
        this.marc21Type = marc21Type;
    }

}
