//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 08:06:18 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.metadata.marc21;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlCData;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * MARC21 Variable Data Fields 010-999
 *
 * <p>
 * Java class for dataFieldType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="dataFieldType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;element name="subfield" type="{http://www.loc.gov/MARC21/slim}subfieldatafieldType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.loc.gov/MARC21/slim}idDataType" /&gt;
 *       &lt;attribute name="tag" use="required" type="{http://www.loc.gov/MARC21/slim}tagDataType" /&gt;
 *       &lt;attribute name="ind1" use="required" type="{http://www.loc.gov/MARC21/slim}indicatorDataType" /&gt;
 *       &lt;attribute name="ind2" use="required" type="{http://www.loc.gov/MARC21/slim}indicatorDataType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "dataFieldType", propOrder = {
                "subfield"
        }
)
@ToString
@EqualsAndHashCode
public class DataFieldType implements Serializable {

    @Serial
    private static final long serialVersionUID = -2226038749187833509L;
    @JacksonXmlElementWrapper(useWrapping = false)
    @JacksonXmlCData
    @XmlElement(required = true)
    protected List<SubfieldatafieldType> subfield;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "tag", required = true)
    protected String tag;
    @XmlAttribute(name = "ind1", required = true)
    protected String ind1;
    @XmlAttribute(name = "ind2", required = true)
    protected String ind2;

    /**
     * Gets the value of the subfield property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the subfield property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getSubfield().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubfieldatafieldType }
     */
    public List<SubfieldatafieldType> getSubfield() {
        if (subfield == null) {
            subfield = new ArrayList<SubfieldatafieldType>();
        }
        return this.subfield;
    }

    public void setSubfield(List<SubfieldatafieldType> subfield) {
        this.subfield = subfield;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the tag property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the ind1 property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInd1() {
        return ind1;
    }

    /**
     * Sets the value of the ind1 property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setInd1(String value) {
        this.ind1 = value;
    }

    /**
     * Gets the value of the ind2 property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInd2() {
        return ind2;
    }

    /**
     * Sets the value of the ind2 property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setInd2(String value) {
        this.ind2 = value;
    }

}
