//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 08:06:18 AM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/MARC21/slim", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.muenchen.oss.oai.pmh.schema.metadata.marc21;
