//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 08:06:18 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.metadata.marc21;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for recordTypeType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="recordTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="Bibliographic"/&gt;
 *     &lt;enumeration value="Authority"/&gt;
 *     &lt;enumeration value="Holdings"/&gt;
 *     &lt;enumeration value="Classification"/&gt;
 *     &lt;enumeration value="Community"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "recordTypeType")
@XmlEnum
public enum RecordTypeType {

    @XmlEnumValue("Bibliographic") BIBLIOGRAPHIC("Bibliographic"),
    @XmlEnumValue("Authority") AUTHORITY("Authority"),
    @XmlEnumValue("Holdings") HOLDINGS(
            "Holdings"),
    @XmlEnumValue("Classification") CLASSIFICATION("Classification"),
    @XmlEnumValue("Community") COMMUNITY("Community");

    private final String value;

    RecordTypeType(String v) {
        value = v;
    }

    public static RecordTypeType fromValue(String v) {
        for (RecordTypeType c : RecordTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
