//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 08:28:04 AM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "http://www.openarchives.org/OAI/2.0/rights/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package de.muenchen.oss.oai.pmh.schema.rights;
