//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 08:28:04 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.rights;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for rightsStatementType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rightsStatementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="rightsReference"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rightsDefinition"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;any namespace='##other'/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "rightsStatementType", propOrder = {
                "rightsReference",
                "rightsDefinition"
        }
)
public class RightsStatementType {

    public RightsReference rightsReference;
    protected RightsDefinition rightsDefinition;

    /**
     * Gets the value of the rightsReference property.
     *
     * @return possible object is
     *         {@link RightsReference }
     */
    public RightsReference getRightsReference() {
        return rightsReference;
    }

    /**
     * Sets the value of the rightsReference property.
     *
     * @param value allowed object is
     *            {@link RightsReference }
     */
    public void setRightsReference(RightsReference value) {
        this.rightsReference = value;
    }

    /**
     * Gets the value of the rightsDefinition property.
     *
     * @return possible object is
     *         {@link RightsDefinition }
     */
    public RightsDefinition getRightsDefinition() {
        return rightsDefinition;
    }

    /**
     * Sets the value of the rightsDefinition property.
     *
     * @param value allowed object is
     *            {@link RightsDefinition }
     */
    public void setRightsDefinition(RightsDefinition value) {
        this.rightsDefinition = value;
    }

}
