//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 08:28:04 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.rights;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for rightsManifestType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rightsManifestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rights" type="{http://www.openarchives.org/OAI/2.0/rights/}rightsStatementType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="appliesTo" type="{http://www.openarchives.org/OAI/2.0/rights/}appliesToType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "rightsManifestType", propOrder = {
                "rights"
        }
)
public class RightsManifestType {

    @XmlAttribute(name = "xmlns")
    public final String xmlns = "http://www.openarchives.org/OAI/2.0/rights/";

    @XmlAttribute(name = "xmlns:xsi")
    public final String xsi = "http://www.w3.org/2001/XMLSchema-instance";

    @XmlAttribute(name = "xsi:schemaLocation")
    public final String schemaLocation = "http://www.openarchives.org/OAI/2.0/rights/ http://www.openarchives.org/OAI/2.0/rightsManifest.xsd";

    @XmlElement(required = true)
    @JacksonXmlElementWrapper(useWrapping = false)
    public List<RightsStatementType> rights;
    @XmlAttribute(name = "appliesTo")
    public String appliesTo;

    /**
     * Gets the value of the rights property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the rights property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getRights().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RightsStatementType }
     */
    public List<RightsStatementType> getRights() {
        if (rights == null) {
            rights = new ArrayList<RightsStatementType>();
        }
        return this.rights;
    }

    /**
     * Gets the value of the appliesTo property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAppliesTo() {
        return appliesTo;
    }

    /**
     * Sets the value of the appliesTo property.
     *
     * @param value allowed object is
     *            {@link String }
     */
    public void setAppliesTo(String value) {
        this.appliesTo = value;
    }

}
