//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.08.31 at 09:34:26 AM CEST
//

package de.muenchen.oss.oai.pmh.starter.webservice.schema.response;

import de.muenchen.oss.oai.pmh.exceptions.OaiPmhException;
import de.muenchen.oss.oai.pmh.schema.*;
import de.muenchen.oss.oai.pmh.starter.webservice.schema.request.Argument;
import de.muenchen.oss.oai.pmh.starter.webservice.schema.request.ParameterParser;
import jakarta.servlet.http.HttpServletRequest;

import java.util.EnumMap;

public class OaiPmhTypeFactory {

    private OaiPmhTypeFactory() {
    }

    private static OaiPmhType createDefaultOaiPmhType(HttpServletRequest request) {
        EnumMap<Argument, String> requestArguments = ParameterParser.parseParameterMapToArgumentEnumMap(request.getParameterMap());
        RequestType requestType = new RequestType();
        requestType.setValue(request.getRequestURL().toString());
        requestType.setFrom(requestArguments.get(Argument.FROM));
        requestType.setIdentifier(requestArguments.get(Argument.IDENTIFIER));
        requestType.setSet(requestArguments.get(Argument.SET));
        requestType.setVerb(VerbType.fromValue(requestArguments.get(Argument.VERB)));
        requestType.setUntil(requestArguments.get(Argument.UNTIL));
        requestType.setMetadataPrefix(requestArguments.get(Argument.METADATA_PREFIX));
        requestType.setResumptionToken(requestArguments.get(Argument.RESUMPTION_TOKEN));

        OaiPmhType oaiPmhType = new OaiPmhType();
        oaiPmhType.setRequest(requestType);
        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhErrorType(HttpServletRequest request, OaiPmhException oaiPmhException) {
        // errorType should not createDefaultOaiPmhType because that could have been the origin or the exception
        OaiPmhType oaiPmhType = new OaiPmhType();

        OaiPmhErrorType oaiPmhErrorType = new OaiPmhErrorType();
        oaiPmhErrorType.setCode(oaiPmhException.getErrorCode());
        oaiPmhErrorType.setValue(oaiPmhException.getMessage());
        oaiPmhType.getError().add(oaiPmhErrorType);
        RequestType requestType = new RequestType();
        requestType.setValue(request.getRequestURL().toString());
        oaiPmhType.setRequest(requestType);

        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhGetRecordResponseType(HttpServletRequest request) {
        OaiPmhType oaiPmhType = createDefaultOaiPmhType(request);

        oaiPmhType.setGetRecord(new GetRecordType());

        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhIdentifyResponseType(HttpServletRequest request) {
        OaiPmhType oaiPmhType = createDefaultOaiPmhType(request);

        oaiPmhType.setIdentify(new IdentifyType());
        oaiPmhType.getIdentify().setBaseURL(request.getRequestURL().toString());

        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhListIdentifiersType(HttpServletRequest request) {
        OaiPmhType oaiPmhType = createDefaultOaiPmhType(request);

        oaiPmhType.setListIdentifiers(new ListIdentifiersType());

        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhListMetaDataFormatsType(HttpServletRequest request) {
        OaiPmhType oaiPmhType = createDefaultOaiPmhType(request);

        oaiPmhType.setListMetadataFormats(new ListMetadataFormatsType());

        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhListRecordsType(HttpServletRequest request) {
        OaiPmhType oaiPmhType = createDefaultOaiPmhType(request);

        oaiPmhType.setListRecords(new ListRecordsType());

        return oaiPmhType;
    }

    public static OaiPmhType createOaiPmhListSetsType(HttpServletRequest request) {
        OaiPmhType oaiPmhType = createDefaultOaiPmhType(request);

        oaiPmhType.setListSets(new ListSetsType());

        return oaiPmhType;
    }

}
