//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 06:57:34 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.oaiidentifier;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the de.muenchen.oss.oai.webservice.schema.response.oaiidentifier package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OaiIdentifier_QNAME = new QName("http://www.openarchives.org/OAI/2.0/oai-identifier", "oai-identifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
     * package: de.muenchen.oss.oai.webservice.schema.response.oaiidentifier
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OaiIdentifierType }
     */
    public OaiIdentifierType createOaiIdentifierType() {
        return new OaiIdentifierType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OaiIdentifierType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link OaiIdentifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/2.0/oai-identifier", name = "oai-identifier")
    public JAXBElement<OaiIdentifierType> createOaiIdentifier(OaiIdentifierType value) {
        return new JAXBElement<OaiIdentifierType>(_OaiIdentifier_QNAME, OaiIdentifierType.class, null, value);
    }

}
