//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 06:43:55 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.eprints;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the de.muenchen.oss.oai.webservice.schema.response.eprints package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Eprints_QNAME = new QName("http://www.openarchives.org/OAI/1.1/eprints", "eprints");
    private final static QName _TextURLTypeURL_QNAME = new QName("http://www.openarchives.org/OAI/1.1/eprints", "URL");
    private final static QName _TextURLTypeText_QNAME = new QName("http://www.openarchives.org/OAI/1.1/eprints", "text");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
     * package: de.muenchen.oss.oai.webservice.schema.response.eprints
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EprintsDescriptionType }
     */
    public EprintsDescriptionType createEprintsDescriptionType() {
        return new EprintsDescriptionType();
    }

    /**
     * Create an instance of {@link TextURLType }
     */
    public TextURLType createTextURLType() {
        return new TextURLType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EprintsDescriptionType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link EprintsDescriptionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/1.1/eprints", name = "eprints")
    public JAXBElement<EprintsDescriptionType> createEprints(EprintsDescriptionType value) {
        return new JAXBElement<EprintsDescriptionType>(_Eprints_QNAME, EprintsDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/1.1/eprints", name = "URL", scope = TextURLType.class)
    public JAXBElement<String> createTextURLTypeURL(String value) {
        return new JAXBElement<String>(_TextURLTypeURL_QNAME, String.class, TextURLType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.openarchives.org/OAI/1.1/eprints", name = "text", scope = TextURLType.class)
    public JAXBElement<String> createTextURLTypeText(String value) {
        return new JAXBElement<String>(_TextURLTypeText_QNAME, String.class, TextURLType.class, value);
    }

}
