//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.23 at 06:43:55 AM CEST
//

package de.muenchen.oss.oai.pmh.schema.eprints;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for TextURLType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TextURLType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "TextURLType", propOrder = {
                "urlOrText"
        }
)
public class TextURLType {

    @XmlElementRefs(
        {
                @XmlElementRef(name = "URL", namespace = "http://www.openarchives.org/OAI/1.1/eprints", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "text", namespace = "http://www.openarchives.org/OAI/1.1/eprints", type = JAXBElement.class, required = false)
        }
    )
    public List<JAXBElement<String>> urlOrText;

    /**
     * Gets the value of the urlOrText property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the urlOrText property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getURLOrText().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public List<JAXBElement<String>> getURLOrText() {
        if (urlOrText == null) {
            urlOrText = new ArrayList<JAXBElement<String>>();
        }
        return this.urlOrText;
    }

}
